version: "2"

services:

  master:
    build:
      context: .
      dockerfile: Dockerfile-master
    container_name: sge_master
    hostname: sge_master
    #network_mode: host
    volumes:
      - .:/dask-drmaa
    command: bash /run-master.sh

  slave-one:
    build:
      context: .
      dockerfile: Dockerfile-slave
    container_name: slave_one
    hostname: slave_one.daskdrmaa_default
    #network_mode: host
    volumes:
      - .:/dask-drmaa
    command: bash /run-slave.sh
    links:
      - "master:sge_master"
    depends_on:
      - master
